import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import {
  Box,
  Button,
  Container,
  Divider,
  Grid,
  Stack,
  Typography,
} from "@mui/material";
import WrapperHeading from "@/components/wrapperheading";
import VideoSection from "@/components/videoSection";
import Experience from "@/components/experience";
import image1 from "@/images/foxconn.png";
import image2 from "@/images/linksys.png";
import image3 from "@/images/belkin.png";
import image4 from "@/images/unacademy.png";
import image5 from "@/images/emami.png";
import image6 from "@/images/graphy.png";
import AuditCard from "@/components/auditCard";
import info from "@/images/info.webp";
import Faq from "@/components/accordion";
import one from "@/images/one.png";
import two from "@/images/two.png";
import three from "@/images/three.png";
import four from "@/images/four.png";
import five from "@/images/five.png";
import RoadMap from "@/components/roadmap";
import Experts from "@/components/expert";
import Footer from "@/components/footer";
export default function Home() {
  const trustedImages = [
    {
      img: image1.src,
    },
    {
      img: image2.src,
    },
    {
      img: image3.src,
    },
    {
      img: image4.src,
    },
    {
      img: image5.src,
    },
    {
      img: image6.src,
    },
  ];

  const audit = [
    {
      img: info.src,
      title:
        "You have a google ads account through which you are running ads for a while",
      color: "#FCE8E5",
    },
    {
      img: info.src,
      title:
        "You are getting clicks, impressions and conversions, so you assume your ads are on point and performing well",
      color: "#FCE8E5",
    },
    {
      img: info.src,
      title:
        "You are not sure whether the current google ads strategy is executed in the right way",
      color: "transparent",
    },
    {
      img: info.src,
      title:
        "You are stuck with okayish results and not sure how to boost the effectiveness of ads or the results",
      color: "transparent",
    },
    {
      img: info.src,
      title:
        "You want to check whether your ads and accounts are well set up and there are areas that needs to be improved",
      color: "#FCE8E5",
    },
    {
      img: info.src,
      title:
        "Your ad conversion, CTR and CPC sucks despite optimising the message and the budget",
      color: "#FCE8E5",
    },
  ];
  const roadMap = [
    {
      img: one.src,
      title: "In-Depth Performance Analysis:",
      description:
        "Your ad costs are going high and they don’t bring necessary website traffic",
      color: "#E8F3EB",
    },
    {
      img: two.src,
      title: "Actionable Optimization Strategies:",
      description:
        "We will highlight growth opportunities you may have missed and give you recommendations tailored to your needs.",
      color: "transparent",
    },
    {
      img: three.src,
      title: "Budget Efficiency Review:",
      description:
        "We’ll discover where you’re wasting ad spend and where to focus your budget to maximise your ROAS.",
      color: "#E8F3EB",
    },
    {
      img: four.src,
      title: "Targeting and Creative Advancements:",
      description:
        "We will give suggestions to refine your audience targeting and ad creatives for better conversions.",
      color: "transparent",
    },
    {
      img: five.src,
      title: "Competitor Analysis:",
      description:
        "We will help with how to stack up your offer against your competitors to seize the market opportunities.",
      color: "#E8F3EB",
    },
  ];
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container sx={{ mt: 5 }}>
        <WrapperHeading bgColor="#E7F0FE">
          {" "}
          <Stack
            sx={{ padding: "8px", textAlign: "center" }}
            direction={{ lg: "row", sm: "column" }}
            alignItems={"center"}
            spacing={1}
            justifyContent={"center"}
          >
            <Typography fontSize={25} fontWeight={600}>
              Marketers/Business Owners - Transform Your Google Ads Spending
              into
            </Typography>
            <Typography fontSize={25} fontWeight={600} color={"#1B72E8"}>
              Real Results!
            </Typography>
          </Stack>
        </WrapperHeading>
        <Box sx={{ mt: 2 }}>
          <Typography
            fontSize={{ lg: 40, sm: 25, xs: 20 }}
            textAlign="center"
            fontWeight={750}
          >
            Give Us Just 30 Minutes, Discover How to Seal Your
          </Typography>

          <Typography
            fontSize={{ lg: 40, sm: 25, xs: 20 }}
            fontWeight={750}
            textAlign={"center"}
          >
            <span style={{ color: "#ff0000", fontWeight: 750 }}>
              {" "}
              Google Ads Leakages
            </span>{" "}
            and <span style={{ color: "#1B72E8" }}>Skyrocket Your ROAS</span>
          </Typography>
        </Box>
        <Box sx={{ mt: { lg: 2, sm: 1 } }}>
          <VideoSection />
        </Box>
      </Container>
      <Box sx={{ backgroundColor: "#F1F7FF", mt: 6, pb: 6 }}>
        <Container sx={{ pt: 6 }}>
          <Typography sx={{ fontSize: 28, fontWeight: 700 }}>
            Get Your Ad Account Audited by an{" "}
            <Typography variant="span" color="#1B72E8">
              Official Google Premier Partner{" "}
            </Typography>
            Who Have..
          </Typography>
          <Stack
            direction={{ lg: "row", sm: "column" }}
            alignItems="center"
            spacing={4}
            mt={4}
            columnGap={2}
            rowGap={4}
          >
            <Experience bgColor={"#1063D3"}>
              {" "}
              <Typography color={"#fff"} fontSize={18} textAlign={"center"}>
                Worked with
              </Typography>
              <Typography
                color="#fff"
                fontSize={45}
                textAlign={"center"}
                fontWeight={550}
              >
                500 +
              </Typography>
              <Typography color={"#fff"} fontSize={18} textAlign="center">
                {" "}
                Brands
              </Typography>
            </Experience>
            <Experience bgColor={"#FFD73A"}>
              {" "}
              <Typography
                color="#000"
                fontSize={45}
                textAlign={"center"}
                fontWeight={550}
              >
                10 +
              </Typography>
              <Typography color={"#000"} fontSize={18} fontWeight={550}>
                Years of Google Ads
              </Typography>
              <Typography
                color={"#000"}
                fontSize={18}
                fontWeight={550}
                textAlign="center"
              >
                {" "}
                Expertise
              </Typography>
            </Experience>
            <Experience bgColor={"#1063D3"}>
              {" "}
              <Typography
                color={"#fff"}
                fontSize={18}
                fontWeight={550}
                textAlign={"center"}
              >
                Spent Over
              </Typography>
              <Typography
                color="#fff"
                fontSize={45}
                textAlign={"center"}
                fontWeight={550}
              >
                150 +
              </Typography>
              <Typography
                color={"#fff"}
                fontSize={18}
                fontWeight={550}
                textAlign="center"
              >
                {" "}
                Crore on Ads
              </Typography>
            </Experience>
            <Experience bgColor={"#FFD73A"}>
              <Typography
                color={"#000"}
                fontSize={18}
                fontWeight={550}
                textAlign={"center"}
              >
                Generated
              </Typography>
              <Typography
                color="#000"
                fontSize={45}
                textAlign={"center"}
                fontWeight={550}
              >
                500 +
              </Typography>
              <Typography
                color={"#000"}
                fontSize={18}
                fontWeight={550}
                textAlign="center"
              >
                Crore Revenue
              </Typography>
            </Experience>
          </Stack>
          <Box sx={{ mt: 7 }}>
            <Typography
              sx={{ textAlign: "center", fontSize: 28, fontWeight: 550 }}
            >
              Trusted by
            </Typography>
          </Box>
          <Grid container sx={{ mt: 3 }}>
            {trustedImages.map((val, i) => (
              <Grid item lg={2} sx={{ margin: "auto" }}>
                <img src={val.img} />
              </Grid>
            ))}
          </Grid>
          <Grid container>
            <Grid item lg={6} margin={"auto"} marginTop={3}>
              <Box sx={{ borderRadius: "20px", backgroundColor: "#000", p: 3 }}>
                <Typography color="#fff" textAlign={"center"} fontSize={21}>
                  Growth Partners showed us that we weren’t even making half of
                  it
                </Typography>
                <Divider
                  sx={{
                    backgroundColor: "#fff",
                    width: "50%",
                    margin: "auto",
                    mt: 3,
                  }}
                />
                <Typography
                  sx={{
                    color: "#fff",
                    fontSize: 18,
                    textAlign: "center",
                    mt: 3,
                  }}
                >
                  " We used to be so happy about our google ads results thinking
                  that we were making 5X ROAS. But when experts at Growth
                  Partners showed us that we weren’t even making half of it, we
                  literally got shocked. But thanks to the audit, we are already
                  seeing huge progress "
                </Typography>

                <Typography
                  sx={{
                    mt: 3,
                    fontSize: 15,
                    color: "#fff",
                    fontWeight: 600,
                    textAlign: "center",
                  }}
                >
                  Nithin Raj
                </Typography>
                <Typography
                  sx={{
                    fontSize: 15,
                    color: "#fff",
                    textAlign: "center",
                  }}
                >
                  Founder, Blue Island
                </Typography>
              </Box>
            </Grid>
          </Grid>
        </Container>
      </Box>
      <Container>
        <Box sx={{ mt: 3 }}>
          <Typography textAlign={"center"} fontSize={38} fontWeight={600}>
            How Do You Know Your Google Ads Need An Audit?
          </Typography>
          <Box sx={{ mt: 3 }}>
            <WrapperHeading bgColor="#E7F0FE">
              <Typography
                sx={{
                  fontSize: { lg: 28, sm: 15 },
                  textAlign: "center",
                  fontWeight: 550,
                }}
              >
                A Google Ads Audit is for You, If You…
              </Typography>
            </WrapperHeading>
          </Box>
          <Grid container spacing={3}>
            {audit.map((val, i) => (
              <Grid item lg={6} key={i} mt={3}>
                <AuditCard
                  border="1px solid #ff0000"
                  img={val.img}
                  bgColor={val.color}
                  heading={val.title}
                />
              </Grid>
            ))}
            <Grid item lg={7} margin={"auto"}>
              <AuditCard
                border="1px solid #ff0000"
                img={info.src}
                bgColor="transparent"
                heading="Your ad costs are going high and they don’t bring necessary website traffic"
              />
            </Grid>
          </Grid>
          <Typography
            sx={{ mt: 3, textAlign: "center", fontSize: 28, fontWeight: 600 }}
          >
            If You Have{" "}
            <Typography variant="span" color={"#1B72E8"}>
              Not Realised These Problems
            </Typography>{" "}
            Yet, It’s Still Not Late.
          </Typography>
          <Box sx={{ mt: 2 }}>
            <WrapperHeading border="1px solid #ff0000" bgColor="#FCE8E5">
              <Typography fontSize={{ lg: 27, sm: 20 }} textAlign="center">
                In fact, 99% of marketers are{" "}
                <Typography variant="span" fontWeight={600}>
                  not even aware that 50% of their ad spend is just waste{" "}
                </Typography>{" "}
                , because of poor management of accounts and the wrong metrics
                they receive!
              </Typography>
            </WrapperHeading>
          </Box>
          <Box sx={{ mt: 2 }}>
            <Grid container>
              <Grid item lg={7} margin={"auto"}>
                <Typography textAlign={"center"} fontSize={22} fontWeight={600}>
                  Do You Want to Take Control of Your Account & Ads Now &{" "}
                  <Typography color={"#34A853"} variant="span">
                    Improve Your ROAS
                  </Typography>{" "}
                  for Real?
                </Typography>
                <Box textAlign={"center"} mt={3}>
                  <Button
                    sx={{
                      backgroundColor: "#0F9D58",
                      color: "#fff",
                      textTransform: "uppercase",
                      p: 1,
                      //   width: "50%",
                      fontSize: 25,
                      fontWeight: 550,
                      ":hover": {
                        backgroundColor: "#0F9D58",
                        color: "#fff",
                      },
                    }}
                  >
                    start my audit now
                  </Button>
                </Box>
                <Typography
                  textAlign={"center"}
                  fontSize={18}
                  mt={2}
                  fontWeight={550}
                >
                  Get Our Expert Audit at a Nominal Fee of Rs.499
                </Typography>
              </Grid>
            </Grid>
          </Box>
        </Box>
      </Container>
      <Box
        sx={{
          mt: 6,
          backgroundColor: "#F8F9FA",
          padding: "20px 0",
        }}
      >
        <Typography
          sx={{
            fontSize: 35,
            fontWeight: 600,
            textAlign: "center",
          }}
        >
          Let Our Experts Manually Check Your Account & <br /> Help You{" "}
          <Typography variant="span" color="#1B72E8">
            Stop Leakages{" "}
          </Typography>
          in Your Funnel
        </Typography>
        <Experts />
      </Box>

      <Grid container mt={4}>
        <Grid item lg={10} margin={"auto"}>
          <Typography
            sx={{ fontSize: 35, fontWeight: 800, textAlign: "center" }}
          >
            Let’s Help You Maximize the Effectiveness of Your Campaigns With Our{" "}
            <Typography variant="span" color="#1B72E8">
              Actionable Insights
            </Typography>
          </Typography>
          <Box sx={{ mt: 3 }}>
            <WrapperHeading bgColor="#2A2A2A">
              <Typography
                textAlign={"center"}
                color={"#fff"}
                fontSize={25}
                fontWeight={550}
              >
                How Will this 30-Minute Audit Help You?
              </Typography>
            </WrapperHeading>
          </Box>
          <Typography fontSize={24} fontWeight={600} mt={3}>
            Our Comprehensive ₹499 Google Ads Audit is not just an assessment;
            it's a{" "}
            <Typography variant="span" color={"#1B72E8"} fontWeight={600}>
              Roadmap to Higher Performance and Smarter Spending
            </Typography>{" "}
            . We dive deep into your account to provide:
          </Typography>
        </Grid>
      </Grid>
      <Grid container>
        <Grid item lg={7} margin={"auto"}>
          <Grid container>
            {roadMap.map((val, i) => (
              <Grid item lg={12} mt={3}>
                <RoadMap
                  title={val.title}
                  heading={val.description}
                  img={val.img}
                  border="1px solid #008000"
                  bgColor={val.color}
                />
              </Grid>
            ))}
          </Grid>
          <Box textAlign={"center"}>
            <Typography
              textAlign={"center"}
              fontSize={18}
              mt={2}
              fontWeight={550}
            >
              Get Our Expert Audit at a Nominal Fee of Rs.499
            </Typography>
          </Box>
          <Box textAlign={"center"} mt={3}>
            <Button
              sx={{
                backgroundColor: "#0F9D58",
                color: "#fff",
                textTransform: "uppercase",
                p: 1,
                //   width: "50%",
                fontSize: 25,
                fontWeight: 550,
                ":hover": {
                  backgroundColor: "#0F9D58",
                  color: "#fff",
                },
              }}
            >
              start my audit now
            </Button>
          </Box>{" "}
        </Grid>
      </Grid>

      <Box sx={{ mt: 3, backgroundColor: "#F8F9FA" }}>
        <Grid container pt={3}>
          <Grid item lg={10} margin={"auto"}>
            <Typography
              fontSize={{ lg: 30,xs:20 }}
              textAlign={"center"}
              fontWeight={600}
              mb={3}
            >
              Frequently Asked Questions
            </Typography>
            <Faq />
          </Grid>
        </Grid>
      </Box>
      <Box sx={{ backgroundColor: "#000" }}>
        <Footer />
      </Box>
    </>
  );
}
